# Generated by Django 2.2.3 on 2019-07-19 02:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190718_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 2, 22, 56, 711805, tzinfo=utc)),
        ),
    ]
